name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - v*.*.*
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm test
